apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp02
spec:
  selector:
    matchLabels:
      app: myapp02
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
      - name: myapp02
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
